openapi: 3.0.1
info:
  title: audit-trail-export-script
  description: Cortex descriptor created automatically by eng-devprod
  x-cortex-tag: audit-trail-export-script
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: cerebrotech/audit-trail-export-script
  x-cortex-owners:
  - name: eng-idsm
    type: group
    provider: OKTA
    description: Updated by eng-devprod
